stages:
  - test
  
# Use images with different versions of Yade by extending templat with image
.test_template:
  stage: test
  image: registry.gitlab.com/yade-dev/docker-prod:$YADE_OS
  variables:
    OUTPUT_DIR: "out_${CI_JOB_ID}_${NTHREADS}"
  before_script:
    - set -euo pipefail
  script:
    # 0. Print info about container
    - echo "Container info:"
    - cat /etc/os-release || true
    - python3 --version || true
    - set -x
    # 1. Verify YADE is installed and check version
    - $YADEBUILD --version

    # 2. Run sipmle simulation, print to screen and file
    - mkdir "$OUTPUT_DIR"
    - cp simWheelSoilBox.py $PARAM_FILE "$OUTPUT_DIR"
    - $YADEBUILD -j${NTHREADS} -x -n simWheelSoilBox.py $PARAM_FILE --params sim.GUImode:false | tee "$OUTPUT_DIR"/log.report
    - cat exec_time.txt
    - mv plot.txt plot.pdf exec_time.txt Data_Output.csv vis "$OUTPUT_DIR"

    # 3. Compare averaged data and show results
    - python3 ./testing/calcAvg.py "$OUTPUT_DIR"/plot.txt --begt $BEGT --endt $ENDT --pRE 4.0 --ref $SAMPLE_PLOT_DATA --compare WxR:6 Vz:10 Fx:40 Fz:4 Slip:4 GrTr:50 z:11 | tee "$OUTPUT_DIR"/log.compare

  artifacts:
    name: ${CI_JOB_NAME}_${CI_PIPELINE_ID}
    when: always
    # This saves the log so you can download it from the GitLab UI
    paths:
      - "$OUTPUT_DIR/"
    expire_in: 1 week


.matrix_yade:
  when: manual
  parallel:
    matrix:
       - YADE_OS: ["debian-trixie", "debian-bookworm", "debian-bullseye", "ubuntu22.04", "ubuntu18.04", "ubuntu16.04"]
         NTHREADS: ["1", "8"]
  variables:
    YADEBUILD: "yade"

.matrix_yadedaily:
  when: manual
  parallel:
    matrix:
       - YADE_OS: ["ubuntu24.04", "debian-bookworm", "debian-bullseye", "ubuntu18.04", "ubuntu16.04"]
         NTHREADS: ["1", "8"]
  variables:
    YADEBUILD: "yadedaily"

# Create jobs for specific images and nthreads by extending the templates
.towed_default:
  extends: .test_template
  variables:
    PARAM_FILE: "params.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_tow0p3mps_2p0kg_y21_j1_pscale10x.txt"
    BEGT: "2.5"
    ENDT: "9"

.towed_Large:
  extends: .test_template
  image: registry.gitlab.com/yade-dev/docker-prod:$YADE_OS
  when: manual
  variables:
    PARAM_FILE: "testing/params_Large_tow0p3mps_1e3kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Large_tow0p3mps_1e3kg_y25_j1.txt"
    BEGT: "2.5"
    ENDT: "9"

towed_default_yade:
  extends:
    - .towed_default
    - .matrix_yade

towed_default_yadedaily:
  extends:
    - .towed_default
    - .matrix_yadedaily

towed_quick_yade:
  extends:
    - .towed_Large
    - .matrix_yade

towed_quick_yadedaily:
  extends:
    - .towed_Large
    - .matrix_yadedaily

.slip06p3_Kyoto_2p0kg:
  extends: .test_template
  when: manual
  variables:
    PARAM_FILE: "testing/params_Kyoto_fSlip06p3_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_fSlip06p3_2p0kg_y25_j1.txt"
    BEGT: "1.75"
    ENDT: "3.5"

slip06p3_Kyoto_yade:
  extends:
    - .slip06p3_Kyoto_2p0kg
    - .matrix_yade

slip06p3_Kyoto_yadedaily:
  extends:
    - .slip06p3_Kyoto_2p0kg
    - .matrix_yadedaily

.slip21p0_Kyoto_2p0kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_fSlip21p0_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_fSlip21p0_2p0kg_y25_j1.txt"
    BEGT: "2"
    ENDT: "3.5"

slip21p0_Kyoto_yade:
  extends:
    - .slip21p0_Kyoto_2p0kg
    - .matrix_yade

slip21p0_Kyoto_yadedaily:
  extends:
    - .slip21p0_Kyoto_2p0kg
    - .matrix_yadedaily

.slip60p_Kyoto_2p0kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_fSlip60p0_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_fSlip60p0_2p0kg_y25_j1.txt"
    BEGT: "3"
    ENDT: "7"

slip60p_Kyoto_yade:
  extends:
    - .slip60p_Kyoto_2p0kg
    - .matrix_yade

slip60p_Kyoto_yadedaily:
  extends:
    - .slip60p_Kyoto_2p0kg
    - .matrix_yadedaily

.slip86p8_Kyoto_1p5kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_fSlip86p8_1p5kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_fSlip86p8_1p5kg_y25_j1.txt"
    BEGT: "10.0"
    ENDT: "16.0"

slip86p8_Kyoto_1p5kg_yade:
  extends:
    - .slip86p8_Kyoto_1p5kg
    - .matrix_yade

slip86p8_Kyoto_1p5kg_yadedaily:
  extends:
    - .slip86p8_Kyoto_1p5kg
    - .matrix_yadedaily

.slip86p8_Kyoto_2p0kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_fSlip86p8_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_fSlip86p8_2p0kg_y25_j1.txt"
    BEGT: "10.0"
    ENDT: "16.0"

slip86p8_Kyoto_yade:
  extends:
    - .slip86p8_Kyoto_2p0kg
    - .matrix_yade

slip86p8_Kyoto_yadedaily:
  extends:
    - .slip86p8_Kyoto_2p0kg
    - .matrix_yadedaily

.tow0p3mps_Kyoto_2p0kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_tow0p3mps_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_tow0p3mps_2p0kg_y25_j1.txt"
    BEGT: "2.5"
    ENDT: "3.5"

tow0p3mps_Kyoto_yade:
  extends:
    - .tow0p3mps_Kyoto_2p0kg
    - .matrix_yade

tow0p3mps_Kyoto_yadedaily:
  extends:
    - .tow0p3mps_Kyoto_2p0kg
    - .matrix_yadedaily

.selfProp_Kyoto_2p0kg:
  extends: .test_template
  variables:
    PARAM_FILE: "testing/params_Kyoto_selfP2p76_2p0kg.json"
    SAMPLE_PLOT_DATA: "testing/plot_Kyoto_selfP2p76_2p0kg_y25_j1.txt"
    BEGT: "2.5"
    ENDT: "3.5"

selfProp_Kyoto_yade:
  extends:
    - .selfProp_Kyoto_2p0kg
    - .matrix_yade

selfProp_Kyoto_yadedaily:
  extends:
    - .selfProp_Kyoto_2p0kg
    - .matrix_yadedaily
